<?php
/**
 * LtiConfiguration1p3Deployment
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * LtiConfiguration1p3Deployment Class Doc Comment
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LtiConfiguration1p3Deployment implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'LtiConfiguration1p3Deployment';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'lti_version' => 'string',
        'organization_id' => 'string',
        'organization_name' => 'string',
        'creator_id' => 'string',
        'creation_date' => '\DateTime',
        'last_used_date' => '\DateTime',
        'status' => 'string',
        'mode' => 'string',
        'platform_iss' => 'string',
        'platform_name' => 'string',
        'client_id' => 'string',
        'deployment_id' => 'string',
        'access_token_url' => 'string',
        'authorization_url' => 'string',
        'jwks_url' => 'string',
        'deployment_mode' => 'string',
        'supported_services' => '\Flat\APIClient\Model\LtiConfiguration1p3BaseSupportedServices',
        'tool' => '\Flat\APIClient\Model\LtiConfiguration1p3BaseTool',
        'public_keyset_url' => 'string',
        'initiate_login_url' => 'string',
        'redirect_uris' => 'string[]',
        'enable_email_matching' => 'bool',
        'parent_id' => 'string',
        'deployment_key' => 'string',
        'deployment_breakdown_by' => 'string',
        'deployment_breakdown_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => null,
        'lti_version' => null,
        'organization_id' => null,
        'organization_name' => null,
        'creator_id' => null,
        'creation_date' => 'date-time',
        'last_used_date' => 'date-time',
        'status' => null,
        'mode' => null,
        'platform_iss' => null,
        'platform_name' => null,
        'client_id' => null,
        'deployment_id' => null,
        'access_token_url' => 'url',
        'authorization_url' => 'url',
        'jwks_url' => 'url',
        'deployment_mode' => null,
        'supported_services' => null,
        'tool' => null,
        'public_keyset_url' => null,
        'initiate_login_url' => null,
        'redirect_uris' => null,
        'enable_email_matching' => null,
        'parent_id' => null,
        'deployment_key' => null,
        'deployment_breakdown_by' => null,
        'deployment_breakdown_id' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'lti_version' => false,
        'organization_id' => false,
        'organization_name' => false,
        'creator_id' => false,
        'creation_date' => false,
        'last_used_date' => false,
        'status' => false,
        'mode' => false,
        'platform_iss' => false,
        'platform_name' => false,
        'client_id' => false,
        'deployment_id' => false,
        'access_token_url' => false,
        'authorization_url' => false,
        'jwks_url' => false,
        'deployment_mode' => false,
        'supported_services' => false,
        'tool' => false,
        'public_keyset_url' => false,
        'initiate_login_url' => false,
        'redirect_uris' => false,
        'enable_email_matching' => false,
        'parent_id' => false,
        'deployment_key' => false,
        'deployment_breakdown_by' => false,
        'deployment_breakdown_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'lti_version' => 'ltiVersion',
        'organization_id' => 'organizationId',
        'organization_name' => 'organizationName',
        'creator_id' => 'creatorId',
        'creation_date' => 'creationDate',
        'last_used_date' => 'lastUsedDate',
        'status' => 'status',
        'mode' => 'mode',
        'platform_iss' => 'platformIss',
        'platform_name' => 'platformName',
        'client_id' => 'clientId',
        'deployment_id' => 'deploymentId',
        'access_token_url' => 'accessTokenUrl',
        'authorization_url' => 'authorizationUrl',
        'jwks_url' => 'jwksUrl',
        'deployment_mode' => 'deploymentMode',
        'supported_services' => 'supportedServices',
        'tool' => 'tool',
        'public_keyset_url' => 'publicKeysetUrl',
        'initiate_login_url' => 'initiateLoginUrl',
        'redirect_uris' => 'redirectUris',
        'enable_email_matching' => 'enableEmailMatching',
        'parent_id' => 'parentId',
        'deployment_key' => 'deploymentKey',
        'deployment_breakdown_by' => 'deploymentBreakdownBy',
        'deployment_breakdown_id' => 'deploymentBreakdownId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'lti_version' => 'setLtiVersion',
        'organization_id' => 'setOrganizationId',
        'organization_name' => 'setOrganizationName',
        'creator_id' => 'setCreatorId',
        'creation_date' => 'setCreationDate',
        'last_used_date' => 'setLastUsedDate',
        'status' => 'setStatus',
        'mode' => 'setMode',
        'platform_iss' => 'setPlatformIss',
        'platform_name' => 'setPlatformName',
        'client_id' => 'setClientId',
        'deployment_id' => 'setDeploymentId',
        'access_token_url' => 'setAccessTokenUrl',
        'authorization_url' => 'setAuthorizationUrl',
        'jwks_url' => 'setJwksUrl',
        'deployment_mode' => 'setDeploymentMode',
        'supported_services' => 'setSupportedServices',
        'tool' => 'setTool',
        'public_keyset_url' => 'setPublicKeysetUrl',
        'initiate_login_url' => 'setInitiateLoginUrl',
        'redirect_uris' => 'setRedirectUris',
        'enable_email_matching' => 'setEnableEmailMatching',
        'parent_id' => 'setParentId',
        'deployment_key' => 'setDeploymentKey',
        'deployment_breakdown_by' => 'setDeploymentBreakdownBy',
        'deployment_breakdown_id' => 'setDeploymentBreakdownId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'lti_version' => 'getLtiVersion',
        'organization_id' => 'getOrganizationId',
        'organization_name' => 'getOrganizationName',
        'creator_id' => 'getCreatorId',
        'creation_date' => 'getCreationDate',
        'last_used_date' => 'getLastUsedDate',
        'status' => 'getStatus',
        'mode' => 'getMode',
        'platform_iss' => 'getPlatformIss',
        'platform_name' => 'getPlatformName',
        'client_id' => 'getClientId',
        'deployment_id' => 'getDeploymentId',
        'access_token_url' => 'getAccessTokenUrl',
        'authorization_url' => 'getAuthorizationUrl',
        'jwks_url' => 'getJwksUrl',
        'deployment_mode' => 'getDeploymentMode',
        'supported_services' => 'getSupportedServices',
        'tool' => 'getTool',
        'public_keyset_url' => 'getPublicKeysetUrl',
        'initiate_login_url' => 'getInitiateLoginUrl',
        'redirect_uris' => 'getRedirectUris',
        'enable_email_matching' => 'getEnableEmailMatching',
        'parent_id' => 'getParentId',
        'deployment_key' => 'getDeploymentKey',
        'deployment_breakdown_by' => 'getDeploymentBreakdownBy',
        'deployment_breakdown_id' => 'getDeploymentBreakdownId'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const LTI_VERSION__1P3 = '1p3';
    public const STATUS_READY_TO_USE = 'ready-to-use';
    public const STATUS_IN_USE = 'in-use';
    public const STATUS_INCOMPLETE_SETUP = 'incomplete-setup';
    public const MODE__1P3_DEPLOYMENT = '1p3-deployment';
    public const DEPLOYMENT_MODE_SINGLE = 'single';
    public const DEPLOYMENT_MODE_MULTI = 'multi';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getLtiVersionAllowableValues()
    {
        return [
            self::LTI_VERSION__1P3,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getStatusAllowableValues()
    {
        return [
            self::STATUS_READY_TO_USE,
            self::STATUS_IN_USE,
            self::STATUS_INCOMPLETE_SETUP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getModeAllowableValues()
    {
        return [
            self::MODE__1P3_DEPLOYMENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getDeploymentModeAllowableValues()
    {
        return [
            self::DEPLOYMENT_MODE_SINGLE,
            self::DEPLOYMENT_MODE_MULTI,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('lti_version', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('organization_name', $data ?? [], null);
        $this->setIfExists('creator_id', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('last_used_date', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('platform_iss', $data ?? [], null);
        $this->setIfExists('platform_name', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('deployment_id', $data ?? [], null);
        $this->setIfExists('access_token_url', $data ?? [], null);
        $this->setIfExists('authorization_url', $data ?? [], null);
        $this->setIfExists('jwks_url', $data ?? [], null);
        $this->setIfExists('deployment_mode', $data ?? [], null);
        $this->setIfExists('supported_services', $data ?? [], null);
        $this->setIfExists('tool', $data ?? [], null);
        $this->setIfExists('public_keyset_url', $data ?? [], null);
        $this->setIfExists('initiate_login_url', $data ?? [], null);
        $this->setIfExists('redirect_uris', $data ?? [], null);
        $this->setIfExists('enable_email_matching', $data ?? [], true);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('deployment_key', $data ?? [], null);
        $this->setIfExists('deployment_breakdown_by', $data ?? [], null);
        $this->setIfExists('deployment_breakdown_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['lti_version'] === null) {
            $invalidProperties[] = "'lti_version' can't be null";
        }
        $allowedValues = self::getLtiVersionAllowableValues();
        if (!is_null($this->container['lti_version']) && !in_array($this->container['lti_version'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lti_version', must be one of '%s'",
                $this->container['lti_version'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        $allowedValues = self::getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = self::getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = self::getDeploymentModeAllowableValues();
        if (!is_null($this->container['deployment_mode']) && !in_array($this->container['deployment_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'deployment_mode', must be one of '%s'",
                $this->container['deployment_mode'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Configuration ID
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets lti_version
     *
     * @return string
     */
    public function getLtiVersion(): string
    {
        return $this->container['lti_version'];
    }

    /**
     * Sets lti_version
     *
     * @param string $lti_version LTI version (1.3)
     *
     * @return $this
     */
    public function setLtiVersion(string $lti_version): static
    {
        if (is_null($lti_version)) {
            throw new InvalidArgumentException('non-nullable lti_version cannot be null');
        }
        $allowedValues = self::getLtiVersionAllowableValues();
        if (!in_array($lti_version, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lti_version', must be one of '%s'",
                    $lti_version,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lti_version'] = $lti_version;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId(): ?string
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id Organization ID
     *
     * @return $this
     */
    public function setOrganizationId(?string $organization_id): static
    {
        if (is_null($organization_id)) {
            throw new InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets organization_name
     *
     * @return string|null
     */
    public function getOrganizationName(): ?string
    {
        return $this->container['organization_name'];
    }

    /**
     * Sets organization_name
     *
     * @param string|null $organization_name Organization name
     *
     * @return $this
     */
    public function setOrganizationName(?string $organization_name): static
    {
        if (is_null($organization_name)) {
            throw new InvalidArgumentException('non-nullable organization_name cannot be null');
        }
        $this->container['organization_name'] = $organization_name;

        return $this;
    }

    /**
     * Gets creator_id
     *
     * @return string|null
     */
    public function getCreatorId(): ?string
    {
        return $this->container['creator_id'];
    }

    /**
     * Sets creator_id
     *
     * @param string|null $creator_id ID of the user who created this configuration
     *
     * @return $this
     */
    public function setCreatorId(?string $creator_id): static
    {
        if (is_null($creator_id)) {
            throw new InvalidArgumentException('non-nullable creator_id cannot be null');
        }
        $this->container['creator_id'] = $creator_id;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime
     */
    public function getCreationDate(): \DateTime
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime $creation_date Configuration creation date
     *
     * @return $this
     */
    public function setCreationDate(\DateTime $creation_date): static
    {
        if (is_null($creation_date)) {
            throw new InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets last_used_date
     *
     * @return \DateTime|null
     */
    public function getLastUsedDate(): ?\DateTime
    {
        return $this->container['last_used_date'];
    }

    /**
     * Sets last_used_date
     *
     * @param \DateTime|null $last_used_date Last time this configuration was used
     *
     * @return $this
     */
    public function setLastUsedDate(?\DateTime $last_used_date): static
    {
        if (is_null($last_used_date)) {
            throw new InvalidArgumentException('non-nullable last_used_date cannot be null');
        }
        $this->container['last_used_date'] = $last_used_date;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Configuration status indicator
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = self::getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode(): ?string
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode Deployment-based LTI 1.3 configuration mode
     *
     * @return $this
     */
    public function setMode(?string $mode): static
    {
        if (is_null($mode)) {
            throw new InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = self::getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets platform_iss
     *
     * @return string|null
     */
    public function getPlatformIss(): ?string
    {
        return $this->container['platform_iss'];
    }

    /**
     * Sets platform_iss
     *
     * @param string|null $platform_iss Platform issuer URL
     *
     * @return $this
     */
    public function setPlatformIss(?string $platform_iss): static
    {
        if (is_null($platform_iss)) {
            throw new InvalidArgumentException('non-nullable platform_iss cannot be null');
        }
        $this->container['platform_iss'] = $platform_iss;

        return $this;
    }

    /**
     * Gets platform_name
     *
     * @return string|null
     */
    public function getPlatformName(): ?string
    {
        return $this->container['platform_name'];
    }

    /**
     * Sets platform_name
     *
     * @param string|null $platform_name Platform display name
     *
     * @return $this
     */
    public function setPlatformName(?string $platform_name): static
    {
        if (is_null($platform_name)) {
            throw new InvalidArgumentException('non-nullable platform_name cannot be null');
        }
        $this->container['platform_name'] = $platform_name;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id OAuth2 client_id allocated by the platform
     *
     * @return $this
     */
    public function setClientId(?string $client_id): static
    {
        if (is_null($client_id)) {
            throw new InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets deployment_id
     *
     * @return string|null
     */
    public function getDeploymentId(): ?string
    {
        return $this->container['deployment_id'];
    }

    /**
     * Sets deployment_id
     *
     * @param string|null $deployment_id Deployment ID linking the tool to a tenant/class (varies by platform)
     *
     * @return $this
     */
    public function setDeploymentId(?string $deployment_id): static
    {
        if (is_null($deployment_id)) {
            throw new InvalidArgumentException('non-nullable deployment_id cannot be null');
        }
        $this->container['deployment_id'] = $deployment_id;

        return $this;
    }

    /**
     * Gets access_token_url
     *
     * @return string|null
     */
    public function getAccessTokenUrl(): ?string
    {
        return $this->container['access_token_url'];
    }

    /**
     * Sets access_token_url
     *
     * @param string|null $access_token_url OAuth2 token endpoint (for AGS/NRPS)
     *
     * @return $this
     */
    public function setAccessTokenUrl(?string $access_token_url): static
    {
        if (is_null($access_token_url)) {
            throw new InvalidArgumentException('non-nullable access_token_url cannot be null');
        }
        $this->container['access_token_url'] = $access_token_url;

        return $this;
    }

    /**
     * Gets authorization_url
     *
     * @return string|null
     */
    public function getAuthorizationUrl(): ?string
    {
        return $this->container['authorization_url'];
    }

    /**
     * Sets authorization_url
     *
     * @param string|null $authorization_url OIDC authorization/login endpoint
     *
     * @return $this
     */
    public function setAuthorizationUrl(?string $authorization_url): static
    {
        if (is_null($authorization_url)) {
            throw new InvalidArgumentException('non-nullable authorization_url cannot be null');
        }
        $this->container['authorization_url'] = $authorization_url;

        return $this;
    }

    /**
     * Gets jwks_url
     *
     * @return string|null
     */
    public function getJwksUrl(): ?string
    {
        return $this->container['jwks_url'];
    }

    /**
     * Sets jwks_url
     *
     * @param string|null $jwks_url Platform JWKS endpoint (public keys)
     *
     * @return $this
     */
    public function setJwksUrl(?string $jwks_url): static
    {
        if (is_null($jwks_url)) {
            throw new InvalidArgumentException('non-nullable jwks_url cannot be null');
        }
        $this->container['jwks_url'] = $jwks_url;

        return $this;
    }

    /**
     * Gets deployment_mode
     *
     * @return string|null
     */
    public function getDeploymentMode(): ?string
    {
        return $this->container['deployment_mode'];
    }

    /**
     * Sets deployment_mode
     *
     * @param string|null $deployment_mode Deployment mode (single for organization-specific, multi for shared parent platforms)
     *
     * @return $this
     */
    public function setDeploymentMode(?string $deployment_mode): static
    {
        if (is_null($deployment_mode)) {
            throw new InvalidArgumentException('non-nullable deployment_mode cannot be null');
        }
        $allowedValues = self::getDeploymentModeAllowableValues();
        if (!in_array($deployment_mode, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'deployment_mode', must be one of '%s'",
                    $deployment_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['deployment_mode'] = $deployment_mode;

        return $this;
    }

    /**
     * Gets supported_services
     *
     * @return \Flat\APIClient\Model\LtiConfiguration1p3BaseSupportedServices|null
     */
    public function getSupportedServices(): ?\Flat\APIClient\Model\LtiConfiguration1p3BaseSupportedServices
    {
        return $this->container['supported_services'];
    }

    /**
     * Sets supported_services
     *
     * @param \Flat\APIClient\Model\LtiConfiguration1p3BaseSupportedServices|null $supported_services supported_services
     *
     * @return $this
     */
    public function setSupportedServices(?\Flat\APIClient\Model\LtiConfiguration1p3BaseSupportedServices $supported_services): static
    {
        if (is_null($supported_services)) {
            throw new InvalidArgumentException('non-nullable supported_services cannot be null');
        }
        $this->container['supported_services'] = $supported_services;

        return $this;
    }

    /**
     * Gets tool
     *
     * @return \Flat\APIClient\Model\LtiConfiguration1p3BaseTool|null
     */
    public function getTool(): ?\Flat\APIClient\Model\LtiConfiguration1p3BaseTool
    {
        return $this->container['tool'];
    }

    /**
     * Sets tool
     *
     * @param \Flat\APIClient\Model\LtiConfiguration1p3BaseTool|null $tool tool
     *
     * @return $this
     */
    public function setTool(?\Flat\APIClient\Model\LtiConfiguration1p3BaseTool $tool): static
    {
        if (is_null($tool)) {
            throw new InvalidArgumentException('non-nullable tool cannot be null');
        }
        $this->container['tool'] = $tool;

        return $this;
    }

    /**
     * Gets public_keyset_url
     *
     * @return string|null
     */
    public function getPublicKeysetUrl(): ?string
    {
        return $this->container['public_keyset_url'];
    }

    /**
     * Sets public_keyset_url
     *
     * @param string|null $public_keyset_url Public keyset URL for the platform to retrieve Flat's public keys
     *
     * @return $this
     */
    public function setPublicKeysetUrl(?string $public_keyset_url): static
    {
        if (is_null($public_keyset_url)) {
            throw new InvalidArgumentException('non-nullable public_keyset_url cannot be null');
        }
        $this->container['public_keyset_url'] = $public_keyset_url;

        return $this;
    }

    /**
     * Gets initiate_login_url
     *
     * @return string|null
     */
    public function getInitiateLoginUrl(): ?string
    {
        return $this->container['initiate_login_url'];
    }

    /**
     * Sets initiate_login_url
     *
     * @param string|null $initiate_login_url URL for the platform to initiate LTI login
     *
     * @return $this
     */
    public function setInitiateLoginUrl(?string $initiate_login_url): static
    {
        if (is_null($initiate_login_url)) {
            throw new InvalidArgumentException('non-nullable initiate_login_url cannot be null');
        }
        $this->container['initiate_login_url'] = $initiate_login_url;

        return $this;
    }

    /**
     * Gets redirect_uris
     *
     * @return string[]|null
     */
    public function getRedirectUris(): ?array
    {
        return $this->container['redirect_uris'];
    }

    /**
     * Sets redirect_uris
     *
     * @param string[]|null $redirect_uris Allowed redirect URIs for LTI launches
     *
     * @return $this
     */
    public function setRedirectUris(?array $redirect_uris): static
    {
        if (is_null($redirect_uris)) {
            throw new InvalidArgumentException('non-nullable redirect_uris cannot be null');
        }
        $this->container['redirect_uris'] = $redirect_uris;

        return $this;
    }

    /**
     * Gets enable_email_matching
     *
     * @return bool|null
     */
    public function getEnableEmailMatching(): ?bool
    {
        return $this->container['enable_email_matching'];
    }

    /**
     * Sets enable_email_matching
     *
     * @param bool|null $enable_email_matching Enable email-based user matching during LTI authentication.  When true (default): If a user with the same email exists in the organization, they will be matched and logged in instead of creating a new account.  When false: Email matching is disabled. Only LTI ID matching is used, which means multiple LTI users can share the same email address and have separate Flat accounts. This is useful for cases like siblings sharing a parent email in the LMS.
     *
     * @return $this
     */
    public function setEnableEmailMatching(?bool $enable_email_matching): static
    {
        if (is_null($enable_email_matching)) {
            throw new InvalidArgumentException('non-nullable enable_email_matching cannot be null');
        }
        $this->container['enable_email_matching'] = $enable_email_matching;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return string|null
     */
    public function getParentId(): ?string
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param string|null $parent_id Parent configuration ID (for deployment-based configs)
     *
     * @return $this
     */
    public function setParentId(?string $parent_id): static
    {
        if (is_null($parent_id)) {
            throw new InvalidArgumentException('non-nullable parent_id cannot be null');
        }
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets deployment_key
     *
     * @return string|null
     */
    public function getDeploymentKey(): ?string
    {
        return $this->container['deployment_key'];
    }

    /**
     * Sets deployment_key
     *
     * @param string|null $deployment_key Deployment key (e.g., schoology, classlink)
     *
     * @return $this
     */
    public function setDeploymentKey(?string $deployment_key): static
    {
        if (is_null($deployment_key)) {
            throw new InvalidArgumentException('non-nullable deployment_key cannot be null');
        }
        $this->container['deployment_key'] = $deployment_key;

        return $this;
    }

    /**
     * Gets deployment_breakdown_by
     *
     * @return string|null
     */
    public function getDeploymentBreakdownBy(): ?string
    {
        return $this->container['deployment_breakdown_by'];
    }

    /**
     * Sets deployment_breakdown_by
     *
     * @param string|null $deployment_breakdown_by Custom claim used for tenant identification (parent platforms only, read-only)
     *
     * @return $this
     */
    public function setDeploymentBreakdownBy(?string $deployment_breakdown_by): static
    {
        if (is_null($deployment_breakdown_by)) {
            throw new InvalidArgumentException('non-nullable deployment_breakdown_by cannot be null');
        }
        $this->container['deployment_breakdown_by'] = $deployment_breakdown_by;

        return $this;
    }

    /**
     * Gets deployment_breakdown_id
     *
     * @return string|null
     */
    public function getDeploymentBreakdownId(): ?string
    {
        return $this->container['deployment_breakdown_id'];
    }

    /**
     * Sets deployment_breakdown_id
     *
     * @param string|null $deployment_breakdown_id Value of the custom claim that identifies this specific tenant (child platforms only)
     *
     * @return $this
     */
    public function setDeploymentBreakdownId(?string $deployment_breakdown_id): static
    {
        if (is_null($deployment_breakdown_id)) {
            throw new InvalidArgumentException('non-nullable deployment_breakdown_id cannot be null');
        }
        $this->container['deployment_breakdown_id'] = $deployment_breakdown_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


