<?php
/**
 * LtiConfigurationUpdate
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * LtiConfigurationUpdate Class Doc Comment
 *
 * @description Update an existing LTI 1.3 configuration (deployment clone or standalone)
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class LtiConfigurationUpdate implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'LtiConfigurationUpdate';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'deployment_id' => 'string',
        'deployment_breakdown_id' => 'string',
        'enable_email_matching' => 'bool',
        'platform_iss' => 'string',
        'platform_name' => 'string',
        'client_id' => 'string',
        'access_token_url' => 'string',
        'authorization_url' => 'string',
        'jwks_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'deployment_id' => null,
        'deployment_breakdown_id' => null,
        'enable_email_matching' => null,
        'platform_iss' => null,
        'platform_name' => null,
        'client_id' => null,
        'access_token_url' => 'url',
        'authorization_url' => 'url',
        'jwks_url' => 'url'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'deployment_id' => false,
        'deployment_breakdown_id' => false,
        'enable_email_matching' => false,
        'platform_iss' => false,
        'platform_name' => false,
        'client_id' => false,
        'access_token_url' => false,
        'authorization_url' => false,
        'jwks_url' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'deployment_id' => 'deploymentId',
        'deployment_breakdown_id' => 'deploymentBreakdownId',
        'enable_email_matching' => 'enableEmailMatching',
        'platform_iss' => 'platformIss',
        'platform_name' => 'platformName',
        'client_id' => 'clientId',
        'access_token_url' => 'accessTokenUrl',
        'authorization_url' => 'authorizationUrl',
        'jwks_url' => 'jwksUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'deployment_id' => 'setDeploymentId',
        'deployment_breakdown_id' => 'setDeploymentBreakdownId',
        'enable_email_matching' => 'setEnableEmailMatching',
        'platform_iss' => 'setPlatformIss',
        'platform_name' => 'setPlatformName',
        'client_id' => 'setClientId',
        'access_token_url' => 'setAccessTokenUrl',
        'authorization_url' => 'setAuthorizationUrl',
        'jwks_url' => 'setJwksUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'deployment_id' => 'getDeploymentId',
        'deployment_breakdown_id' => 'getDeploymentBreakdownId',
        'enable_email_matching' => 'getEnableEmailMatching',
        'platform_iss' => 'getPlatformIss',
        'platform_name' => 'getPlatformName',
        'client_id' => 'getClientId',
        'access_token_url' => 'getAccessTokenUrl',
        'authorization_url' => 'getAuthorizationUrl',
        'jwks_url' => 'getJwksUrl'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('deployment_id', $data ?? [], null);
        $this->setIfExists('deployment_breakdown_id', $data ?? [], null);
        $this->setIfExists('enable_email_matching', $data ?? [], null);
        $this->setIfExists('platform_iss', $data ?? [], null);
        $this->setIfExists('platform_name', $data ?? [], null);
        $this->setIfExists('client_id', $data ?? [], null);
        $this->setIfExists('access_token_url', $data ?? [], null);
        $this->setIfExists('authorization_url', $data ?? [], null);
        $this->setIfExists('jwks_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets deployment_id
     *
     * @return string|null
     */
    public function getDeploymentId(): ?string
    {
        return $this->container['deployment_id'];
    }

    /**
     * Sets deployment_id
     *
     * @param string|null $deployment_id Deployment identifier provided by the platform
     *
     * @return $this
     */
    public function setDeploymentId(?string $deployment_id): static
    {
        if (is_null($deployment_id)) {
            throw new InvalidArgumentException('non-nullable deployment_id cannot be null');
        }
        $this->container['deployment_id'] = $deployment_id;

        return $this;
    }

    /**
     * Gets deployment_breakdown_id
     *
     * @return string|null
     */
    public function getDeploymentBreakdownId(): ?string
    {
        return $this->container['deployment_breakdown_id'];
    }

    /**
     * Sets deployment_breakdown_id
     *
     * @param string|null $deployment_breakdown_id Specific tenant identifier for multi-tenant platforms
     *
     * @return $this
     */
    public function setDeploymentBreakdownId(?string $deployment_breakdown_id): static
    {
        if (is_null($deployment_breakdown_id)) {
            throw new InvalidArgumentException('non-nullable deployment_breakdown_id cannot be null');
        }
        $this->container['deployment_breakdown_id'] = $deployment_breakdown_id;

        return $this;
    }

    /**
     * Gets enable_email_matching
     *
     * @return bool|null
     */
    public function getEnableEmailMatching(): ?bool
    {
        return $this->container['enable_email_matching'];
    }

    /**
     * Sets enable_email_matching
     *
     * @param bool|null $enable_email_matching Enable email-based user matching during LTI authentication
     *
     * @return $this
     */
    public function setEnableEmailMatching(?bool $enable_email_matching): static
    {
        if (is_null($enable_email_matching)) {
            throw new InvalidArgumentException('non-nullable enable_email_matching cannot be null');
        }
        $this->container['enable_email_matching'] = $enable_email_matching;

        return $this;
    }

    /**
     * Gets platform_iss
     *
     * @return string|null
     */
    public function getPlatformIss(): ?string
    {
        return $this->container['platform_iss'];
    }

    /**
     * Sets platform_iss
     *
     * @param string|null $platform_iss Platform issuer URL
     *
     * @return $this
     */
    public function setPlatformIss(?string $platform_iss): static
    {
        if (is_null($platform_iss)) {
            throw new InvalidArgumentException('non-nullable platform_iss cannot be null');
        }
        $this->container['platform_iss'] = $platform_iss;

        return $this;
    }

    /**
     * Gets platform_name
     *
     * @return string|null
     */
    public function getPlatformName(): ?string
    {
        return $this->container['platform_name'];
    }

    /**
     * Sets platform_name
     *
     * @param string|null $platform_name Platform display name
     *
     * @return $this
     */
    public function setPlatformName(?string $platform_name): static
    {
        if (is_null($platform_name)) {
            throw new InvalidArgumentException('non-nullable platform_name cannot be null');
        }
        $this->container['platform_name'] = $platform_name;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id OAuth2 client_id allocated by the platform
     *
     * @return $this
     */
    public function setClientId(?string $client_id): static
    {
        if (is_null($client_id)) {
            throw new InvalidArgumentException('non-nullable client_id cannot be null');
        }
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets access_token_url
     *
     * @return string|null
     */
    public function getAccessTokenUrl(): ?string
    {
        return $this->container['access_token_url'];
    }

    /**
     * Sets access_token_url
     *
     * @param string|null $access_token_url Platform access token endpoint URL
     *
     * @return $this
     */
    public function setAccessTokenUrl(?string $access_token_url): static
    {
        if (is_null($access_token_url)) {
            throw new InvalidArgumentException('non-nullable access_token_url cannot be null');
        }
        $this->container['access_token_url'] = $access_token_url;

        return $this;
    }

    /**
     * Gets authorization_url
     *
     * @return string|null
     */
    public function getAuthorizationUrl(): ?string
    {
        return $this->container['authorization_url'];
    }

    /**
     * Sets authorization_url
     *
     * @param string|null $authorization_url Platform OIDC authorization endpoint URL
     *
     * @return $this
     */
    public function setAuthorizationUrl(?string $authorization_url): static
    {
        if (is_null($authorization_url)) {
            throw new InvalidArgumentException('non-nullable authorization_url cannot be null');
        }
        $this->container['authorization_url'] = $authorization_url;

        return $this;
    }

    /**
     * Gets jwks_url
     *
     * @return string|null
     */
    public function getJwksUrl(): ?string
    {
        return $this->container['jwks_url'];
    }

    /**
     * Sets jwks_url
     *
     * @param string|null $jwks_url Platform JWKS endpoint URL for public keys
     *
     * @return $this
     */
    public function setJwksUrl(?string $jwks_url): static
    {
        if (is_null($jwks_url)) {
            throw new InvalidArgumentException('non-nullable jwks_url cannot be null');
        }
        $this->container['jwks_url'] = $jwks_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


