<?php
/**
 * ScoreCreationFileImport
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * ScoreCreationFileImport Class Doc Comment
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScoreCreationFileImport implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScoreCreationFileImport';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'title' => 'string',
        'privacy' => '\Flat\APIClient\Model\ScorePrivacy',
        'collection' => 'string',
        'google_drive_folder' => 'string',
        'filename' => 'string',
        'data' => 'string',
        'data_encoding' => 'string',
        'supports_tasks' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'title' => null,
        'privacy' => null,
        'collection' => null,
        'google_drive_folder' => null,
        'filename' => null,
        'data' => null,
        'data_encoding' => null,
        'supports_tasks' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'title' => false,
        'privacy' => false,
        'collection' => false,
        'google_drive_folder' => false,
        'filename' => false,
        'data' => false,
        'data_encoding' => false,
        'supports_tasks' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'title' => 'title',
        'privacy' => 'privacy',
        'collection' => 'collection',
        'google_drive_folder' => 'googleDriveFolder',
        'filename' => 'filename',
        'data' => 'data',
        'data_encoding' => 'dataEncoding',
        'supports_tasks' => 'supportsTasks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'title' => 'setTitle',
        'privacy' => 'setPrivacy',
        'collection' => 'setCollection',
        'google_drive_folder' => 'setGoogleDriveFolder',
        'filename' => 'setFilename',
        'data' => 'setData',
        'data_encoding' => 'setDataEncoding',
        'supports_tasks' => 'setSupportsTasks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'title' => 'getTitle',
        'privacy' => 'getPrivacy',
        'collection' => 'getCollection',
        'google_drive_folder' => 'getGoogleDriveFolder',
        'filename' => 'getFilename',
        'data' => 'getData',
        'data_encoding' => 'getDataEncoding',
        'supports_tasks' => 'getSupportsTasks'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DATA_ENCODING_BASE64 = 'base64';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getDataEncodingAllowableValues()
    {
        return [
            self::DATA_ENCODING_BASE64,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('privacy', $data ?? [], null);
        $this->setIfExists('collection', $data ?? [], null);
        $this->setIfExists('google_drive_folder', $data ?? [], null);
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('data_encoding', $data ?? [], null);
        $this->setIfExists('supports_tasks', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['data'] === null) {
            $invalidProperties[] = "'data' can't be null";
        }
        $allowedValues = self::getDataEncodingAllowableValues();
        if (!is_null($this->container['data_encoding']) && !in_array($this->container['data_encoding'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'data_encoding', must be one of '%s'",
                $this->container['data_encoding'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The title of the new score. If the title is too long, the API may trim this one.  If this title is not specified, the API will try to (in this order):   - Use the title contained in the file (e.g. [`movement-title`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-movement-title.htm) or [`credit-words`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-credit-words.htm) for [MusicXML](http://www.musicxml.com/) files).   - Use the name of the file for files from a specified `source` (e.g. Google Drive) or the one in the `filename` property   - Set a default title (e.g. \"New Music Score\")
     *
     * @return $this
     */
    public function setTitle(?string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets privacy
     *
     * @return \Flat\APIClient\Model\ScorePrivacy|null
     */
    public function getPrivacy(): ?\Flat\APIClient\Model\ScorePrivacy
    {
        return $this->container['privacy'];
    }

    /**
     * Sets privacy
     *
     * @param \Flat\APIClient\Model\ScorePrivacy|null $privacy privacy
     *
     * @return $this
     */
    public function setPrivacy(?\Flat\APIClient\Model\ScorePrivacy $privacy): static
    {
        if (is_null($privacy)) {
            throw new InvalidArgumentException('non-nullable privacy cannot be null');
        }
        $this->container['privacy'] = $privacy;

        return $this;
    }

    /**
     * Gets collection
     *
     * @return string|null
     */
    public function getCollection(): ?string
    {
        return $this->container['collection'];
    }

    /**
     * Sets collection
     *
     * @param string|null $collection Unique identifier of a collection where the score will be created. If no collection identifier is provided, the score will not be added to any collection and will only be visible in the `allScores` virtual collection.
     *
     * @return $this
     */
    public function setCollection(?string $collection): static
    {
        if (is_null($collection)) {
            throw new InvalidArgumentException('non-nullable collection cannot be null');
        }
        $this->container['collection'] = $collection;

        return $this;
    }

    /**
     * Gets google_drive_folder
     *
     * @return string|null
     */
    public function getGoogleDriveFolder(): ?string
    {
        return $this->container['google_drive_folder'];
    }

    /**
     * Sets google_drive_folder
     *
     * @param string|null $google_drive_folder If the user uses Google Drive and this properties is specified, the file will be created in this directory. The currently user creating the file must be granted to write in this directory.
     *
     * @return $this
     */
    public function setGoogleDriveFolder(?string $google_drive_folder): static
    {
        if (is_null($google_drive_folder)) {
            throw new InvalidArgumentException('non-nullable google_drive_folder cannot be null');
        }
        $this->container['google_drive_folder'] = $google_drive_folder;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename If this is an imported file, its filename
     *
     * @return $this
     */
    public function setFilename(?string $filename): static
    {
        if (is_null($filename)) {
            throw new InvalidArgumentException('non-nullable filename cannot be null');
        }
        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets data
     *
     * @return string
     */
    public function getData(): string
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param string $data The data of the score file. See the `POST /scores` endpoint description for the full list of supported formats. Binary payloads (e.g. compressed MusicXML, MIDI, Guitar Pro) can be encoded in Base64, in this case the `dataEncoding` property must match the encoding used for the API request.
     *
     * @return $this
     */
    public function setData(string $data): static
    {
        if (is_null($data)) {
            throw new InvalidArgumentException('non-nullable data cannot be null');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets data_encoding
     *
     * @return string|null
     */
    public function getDataEncoding(): ?string
    {
        return $this->container['data_encoding'];
    }

    /**
     * Sets data_encoding
     *
     * @param string|null $data_encoding The optional encoding of the score data. This property must match the encoding used for the `data` property.
     *
     * @return $this
     */
    public function setDataEncoding(?string $data_encoding): static
    {
        if (is_null($data_encoding)) {
            throw new InvalidArgumentException('non-nullable data_encoding cannot be null');
        }
        $allowedValues = self::getDataEncodingAllowableValues();
        if (!in_array($data_encoding, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'data_encoding', must be one of '%s'",
                    $data_encoding,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['data_encoding'] = $data_encoding;

        return $this;
    }

    /**
     * Gets supports_tasks
     *
     * @return bool|null
     */
    public function getSupportsTasks(): ?bool
    {
        return $this->container['supports_tasks'];
    }

    /**
     * Sets supports_tasks
     *
     * @param bool|null $supports_tasks Set this to `true` if the client supports asynchronous task flows. When importing a score that requires OMR processing (a PDF or a page image), the API will return a 202 Accepted response along with a task reference. The client can then check the task status using the endpoint `GET /v2/tasks/{task}`.
     *
     * @return $this
     */
    public function setSupportsTasks(?bool $supports_tasks): static
    {
        if (is_null($supports_tasks)) {
            throw new InvalidArgumentException('non-nullable supports_tasks cannot be null');
        }
        $this->container['supports_tasks'] = $supports_tasks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


