<?php
/**
 * ScoreTrack
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.2
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * ScoreTrack Class Doc Comment
 *
 * @description An audio track for a score
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScoreTrack implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScoreTrack';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'title' => 'string',
        'score' => 'string',
        'creator' => 'string',
        'creation_date' => '\DateTime',
        'modification_date' => '\DateTime',
        'default' => 'bool',
        'state' => '\Flat\APIClient\Model\ScoreTrackState',
        'type' => '\Flat\APIClient\Model\ScoreTrackType',
        'purpose' => '\Flat\APIClient\Model\ScoreTrackPurpose',
        'url' => 'string',
        'media_id' => 'string',
        'synchronization_points' => '\Flat\APIClient\Model\ScoreTrackPoint[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => null,
        'title' => null,
        'score' => null,
        'creator' => null,
        'creation_date' => 'date-time',
        'modification_date' => 'date-time',
        'default' => null,
        'state' => null,
        'type' => null,
        'purpose' => null,
        'url' => null,
        'media_id' => null,
        'synchronization_points' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'title' => false,
        'score' => false,
        'creator' => false,
        'creation_date' => false,
        'modification_date' => false,
        'default' => false,
        'state' => false,
        'type' => false,
        'purpose' => false,
        'url' => false,
        'media_id' => false,
        'synchronization_points' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'score' => 'score',
        'creator' => 'creator',
        'creation_date' => 'creationDate',
        'modification_date' => 'modificationDate',
        'default' => 'default',
        'state' => 'state',
        'type' => 'type',
        'purpose' => 'purpose',
        'url' => 'url',
        'media_id' => 'mediaId',
        'synchronization_points' => 'synchronizationPoints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'score' => 'setScore',
        'creator' => 'setCreator',
        'creation_date' => 'setCreationDate',
        'modification_date' => 'setModificationDate',
        'default' => 'setDefault',
        'state' => 'setState',
        'type' => 'setType',
        'purpose' => 'setPurpose',
        'url' => 'setUrl',
        'media_id' => 'setMediaId',
        'synchronization_points' => 'setSynchronizationPoints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'score' => 'getScore',
        'creator' => 'getCreator',
        'creation_date' => 'getCreationDate',
        'modification_date' => 'getModificationDate',
        'default' => 'getDefault',
        'state' => 'getState',
        'type' => 'getType',
        'purpose' => 'getPurpose',
        'url' => 'getUrl',
        'media_id' => 'getMediaId',
        'synchronization_points' => 'getSynchronizationPoints'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('score', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('modification_date', $data ?? [], null);
        $this->setIfExists('default', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('purpose', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('media_id', $data ?? [], null);
        $this->setIfExists('synchronization_points', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['creator'] === null) {
            $invalidProperties[] = "'creator' can't be null";
        }
        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        if ($this->container['modification_date'] === null) {
            $invalidProperties[] = "'modification_date' can't be null";
        }
        if ($this->container['default'] === null) {
            $invalidProperties[] = "'default' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['purpose'] === null) {
            $invalidProperties[] = "'purpose' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The unique identifier of the score track
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Title of the track
     *
     * @return $this
     */
    public function setTitle(?string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets score
     *
     * @return string|null
     */
    public function getScore(): ?string
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param string|null $score The unique identifier of the score. Absent for Free Record performance submissions, which are recorded without an attached score.
     *
     * @return $this
     */
    public function setScore(?string $score): static
    {
        if (is_null($score)) {
            throw new InvalidArgumentException('non-nullable score cannot be null');
        }
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return string
     */
    public function getCreator(): string
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param string $creator The unique identifier of the track creator
     *
     * @return $this
     */
    public function setCreator(string $creator): static
    {
        if (is_null($creator)) {
            throw new InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime
     */
    public function getCreationDate(): \DateTime
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime $creation_date The creation date of the track
     *
     * @return $this
     */
    public function setCreationDate(\DateTime $creation_date): static
    {
        if (is_null($creation_date)) {
            throw new InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets modification_date
     *
     * @return \DateTime
     */
    public function getModificationDate(): \DateTime
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     *
     * @param \DateTime $modification_date The modification date of the track
     *
     * @return $this
     */
    public function setModificationDate(\DateTime $modification_date): static
    {
        if (is_null($modification_date)) {
            throw new InvalidArgumentException('non-nullable modification_date cannot be null');
        }
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets default
     *
     * @return bool
     */
    public function getDefault(): bool
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param bool $default True if the track should be used as default audio source
     *
     * @return $this
     */
    public function setDefault(bool $default): static
    {
        if (is_null($default)) {
            throw new InvalidArgumentException('non-nullable default cannot be null');
        }
        $this->container['default'] = $default;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \Flat\APIClient\Model\ScoreTrackState
     */
    public function getState(): \Flat\APIClient\Model\ScoreTrackState
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \Flat\APIClient\Model\ScoreTrackState $state state
     *
     * @return $this
     */
    public function setState(\Flat\APIClient\Model\ScoreTrackState $state): static
    {
        if (is_null($state)) {
            throw new InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Flat\APIClient\Model\ScoreTrackType
     */
    public function getType(): \Flat\APIClient\Model\ScoreTrackType
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Flat\APIClient\Model\ScoreTrackType $type type
     *
     * @return $this
     */
    public function setType(\Flat\APIClient\Model\ScoreTrackType $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets purpose
     *
     * @return \Flat\APIClient\Model\ScoreTrackPurpose
     */
    public function getPurpose(): \Flat\APIClient\Model\ScoreTrackPurpose
    {
        return $this->container['purpose'];
    }

    /**
     * Sets purpose
     *
     * @param \Flat\APIClient\Model\ScoreTrackPurpose $purpose purpose
     *
     * @return $this
     */
    public function setPurpose(\Flat\APIClient\Model\ScoreTrackPurpose $purpose): static
    {
        if (is_null($purpose)) {
            throw new InvalidArgumentException('non-nullable purpose cannot be null');
        }
        $this->container['purpose'] = $purpose;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl(): ?string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url The URL of the track
     *
     * @return $this
     */
    public function setUrl(?string $url): static
    {
        if (is_null($url)) {
            throw new InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets media_id
     *
     * @return string|null
     */
    public function getMediaId(): ?string
    {
        return $this->container['media_id'];
    }

    /**
     * Sets media_id
     *
     * @param string|null $media_id The unique identifier of the track when hosted on an external service. For example, if the url is `https://www.youtube.com/watch?v=dQw4w9WgXcQ`, `mediaId` will be `dQw4w9WgXcQ`
     *
     * @return $this
     */
    public function setMediaId(?string $media_id): static
    {
        if (is_null($media_id)) {
            throw new InvalidArgumentException('non-nullable media_id cannot be null');
        }
        $this->container['media_id'] = $media_id;

        return $this;
    }

    /**
     * Gets synchronization_points
     *
     * @return \Flat\APIClient\Model\ScoreTrackPoint[]|null
     */
    public function getSynchronizationPoints(): ?array
    {
        return $this->container['synchronization_points'];
    }

    /**
     * Sets synchronization_points
     *
     * @param \Flat\APIClient\Model\ScoreTrackPoint[]|null $synchronization_points synchronization_points
     *
     * @return $this
     */
    public function setSynchronizationPoints(?array $synchronization_points): static
    {
        if (is_null($synchronization_points)) {
            throw new InvalidArgumentException('non-nullable synchronization_points cannot be null');
        }
        $this->container['synchronization_points'] = $synchronization_points;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


