<?php
/**
 * ScoreCommentUpdate
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * ScoreCommentUpdate Class Doc Comment
 *
 * @description Update of a comment
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScoreCommentUpdate implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScoreCommentUpdate';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'revision' => 'string',
        'comment' => 'string',
        'raw_comment' => 'string',
        'context' => '\Flat\APIClient\Model\ScoreCommentContext'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'revision' => null,
        'comment' => null,
        'raw_comment' => null,
        'context' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'revision' => false,
        'comment' => false,
        'raw_comment' => false,
        'context' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'revision' => 'revision',
        'comment' => 'comment',
        'raw_comment' => 'rawComment',
        'context' => 'context'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'revision' => 'setRevision',
        'comment' => 'setComment',
        'raw_comment' => 'setRawComment',
        'context' => 'setContext'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'revision' => 'getRevision',
        'comment' => 'getComment',
        'raw_comment' => 'getRawComment',
        'context' => 'getContext'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('revision', $data ?? [], null);
        $this->setIfExists('comment', $data ?? [], null);
        $this->setIfExists('raw_comment', $data ?? [], null);
        $this->setIfExists('context', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['comment']) && (mb_strlen($this->container['comment']) > 10000)) {
            $invalidProperties[] = "invalid value for 'comment', the character length must be smaller than or equal to 10000.";
        }

        if (!is_null($this->container['comment']) && (mb_strlen($this->container['comment']) < 1)) {
            $invalidProperties[] = "invalid value for 'comment', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['raw_comment']) && (mb_strlen($this->container['raw_comment']) > 10000)) {
            $invalidProperties[] = "invalid value for 'raw_comment', the character length must be smaller than or equal to 10000.";
        }

        if (!is_null($this->container['raw_comment']) && (mb_strlen($this->container['raw_comment']) < 1)) {
            $invalidProperties[] = "invalid value for 'raw_comment', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets revision
     *
     * @return string|null
     */
    public function getRevision(): ?string
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param string|null $revision The unique identifier of the revision of the score where the comment was added. If this property is unspecified or contains \"last\", the API will automatically take the last revision created.
     *
     * @return $this
     */
    public function setRevision(?string $revision): static
    {
        if (is_null($revision)) {
            throw new InvalidArgumentException('non-nullable revision cannot be null');
        }
        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment The comment text that can includes mentions using the following format: `@[id:username]`.
     *
     * @return $this
     */
    public function setComment(?string $comment): static
    {
        if (is_null($comment)) {
            throw new InvalidArgumentException('non-nullable comment cannot be null');
        }
        if ((mb_strlen($comment) > 10000)) {
            throw new InvalidArgumentException('invalid length for $comment when calling ScoreCommentUpdate., must be smaller than or equal to 10000.');
        }
        if ((mb_strlen($comment) < 1)) {
            throw new InvalidArgumentException('invalid length for $comment when calling ScoreCommentUpdate., must be bigger than or equal to 1.');
        }

        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets raw_comment
     *
     * @return string|null
     */
    public function getRawComment(): ?string
    {
        return $this->container['raw_comment'];
    }

    /**
     * Sets raw_comment
     *
     * @param string|null $raw_comment A raw version of the comment, that can be displayed without the mentions. If you use mentions, this property must be set.
     *
     * @return $this
     */
    public function setRawComment(?string $raw_comment): static
    {
        if (is_null($raw_comment)) {
            throw new InvalidArgumentException('non-nullable raw_comment cannot be null');
        }
        if ((mb_strlen($raw_comment) > 10000)) {
            throw new InvalidArgumentException('invalid length for $raw_comment when calling ScoreCommentUpdate., must be smaller than or equal to 10000.');
        }
        if ((mb_strlen($raw_comment) < 1)) {
            throw new InvalidArgumentException('invalid length for $raw_comment when calling ScoreCommentUpdate., must be bigger than or equal to 1.');
        }

        $this->container['raw_comment'] = $raw_comment;

        return $this;
    }

    /**
     * Gets context
     *
     * @return \Flat\APIClient\Model\ScoreCommentContext|null
     */
    public function getContext(): ?\Flat\APIClient\Model\ScoreCommentContext
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param \Flat\APIClient\Model\ScoreCommentContext|null $context context
     *
     * @return $this
     */
    public function setContext(?\Flat\APIClient\Model\ScoreCommentContext $context): static
    {
        if (is_null($context)) {
            throw new InvalidArgumentException('non-nullable context cannot be null');
        }
        $this->container['context'] = $context;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


