<?php
/**
 * ScoreDetails
 *
 * PHP version 8.1
 *
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flat API
 *
 * The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html)
 *
 * The version of the OpenAPI document: 2.26.1
 * Contact: developers@flat.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flat\APIClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Flat\APIClient\ObjectSerializer;

/**
 * ScoreDetails Class Doc Comment
 *
 * @description The score and all its details
 * @package  Flat\APIClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ScoreDetails implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ScoreDetails';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'id' => 'string',
        'sharing_key' => 'string',
        'title' => 'string',
        'privacy' => '\Flat\APIClient\Model\ScorePrivacy',
        'user' => '\Flat\APIClient\Model\UserPublic',
        'html_url' => 'string',
        'edit_html_url' => 'string',
        'subtitle' => 'string',
        'lyricist' => 'string',
        'arranger' => 'string',
        'composer' => 'string',
        'description' => 'string',
        'tags' => 'string[]',
        'creation_type' => '\Flat\APIClient\Model\ScoreCreationType',
        'license' => '\Flat\APIClient\Model\ScoreLicense',
        'license_text' => 'string',
        'duration_time' => 'float',
        'number_measures' => 'int',
        'main_tempo_qpm' => 'float',
        'main_key_signature' => 'float',
        'rights' => '\Flat\APIClient\Model\ResourceRights',
        'collaborators' => '\Flat\APIClient\Model\ResourceCollaborator[]',
        'creation_date' => '\DateTime',
        'modification_date' => '\DateTime',
        'publication_date' => '\DateTime',
        'scheduled_deletion_date' => '\DateTime',
        'highlighted_date' => '\DateTime',
        'organization' => 'string',
        'parent_score' => 'string',
        'instruments' => 'string[]',
        'instruments_names' => 'string[]',
        'samples' => 'string[]',
        'google_drive_file_id' => 'string',
        'likes' => '\Flat\APIClient\Model\ScoreLikesCounts',
        'comments' => '\Flat\APIClient\Model\ScoreCommentsCounts',
        'views' => '\Flat\APIClient\Model\ScoreViewsCounts',
        'plays' => '\Flat\APIClient\Model\ScorePlaysCounts',
        'collections' => 'string[]',
        'me' => '\Flat\APIClient\Model\ScoreDetailsAllOfMe'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'id' => null,
        'sharing_key' => null,
        'title' => null,
        'privacy' => null,
        'user' => null,
        'html_url' => 'url',
        'edit_html_url' => 'url',
        'subtitle' => null,
        'lyricist' => null,
        'arranger' => null,
        'composer' => null,
        'description' => null,
        'tags' => null,
        'creation_type' => null,
        'license' => null,
        'license_text' => null,
        'duration_time' => null,
        'number_measures' => null,
        'main_tempo_qpm' => null,
        'main_key_signature' => null,
        'rights' => null,
        'collaborators' => null,
        'creation_date' => 'date-time',
        'modification_date' => 'date-time',
        'publication_date' => 'date-time',
        'scheduled_deletion_date' => 'date-time',
        'highlighted_date' => 'date-time',
        'organization' => null,
        'parent_score' => null,
        'instruments' => null,
        'instruments_names' => null,
        'samples' => null,
        'google_drive_file_id' => null,
        'likes' => null,
        'comments' => null,
        'views' => null,
        'plays' => null,
        'collections' => null,
        'me' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'id' => false,
        'sharing_key' => false,
        'title' => false,
        'privacy' => false,
        'user' => false,
        'html_url' => false,
        'edit_html_url' => false,
        'subtitle' => false,
        'lyricist' => false,
        'arranger' => false,
        'composer' => false,
        'description' => false,
        'tags' => false,
        'creation_type' => true,
        'license' => true,
        'license_text' => false,
        'duration_time' => false,
        'number_measures' => false,
        'main_tempo_qpm' => false,
        'main_key_signature' => false,
        'rights' => false,
        'collaborators' => false,
        'creation_date' => false,
        'modification_date' => false,
        'publication_date' => false,
        'scheduled_deletion_date' => false,
        'highlighted_date' => false,
        'organization' => false,
        'parent_score' => false,
        'instruments' => false,
        'instruments_names' => false,
        'samples' => false,
        'google_drive_file_id' => false,
        'likes' => false,
        'comments' => false,
        'views' => false,
        'plays' => false,
        'collections' => false,
        'me' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'sharing_key' => 'sharingKey',
        'title' => 'title',
        'privacy' => 'privacy',
        'user' => 'user',
        'html_url' => 'htmlUrl',
        'edit_html_url' => 'editHtmlUrl',
        'subtitle' => 'subtitle',
        'lyricist' => 'lyricist',
        'arranger' => 'arranger',
        'composer' => 'composer',
        'description' => 'description',
        'tags' => 'tags',
        'creation_type' => 'creationType',
        'license' => 'license',
        'license_text' => 'licenseText',
        'duration_time' => 'durationTime',
        'number_measures' => 'numberMeasures',
        'main_tempo_qpm' => 'mainTempoQpm',
        'main_key_signature' => 'mainKeySignature',
        'rights' => 'rights',
        'collaborators' => 'collaborators',
        'creation_date' => 'creationDate',
        'modification_date' => 'modificationDate',
        'publication_date' => 'publicationDate',
        'scheduled_deletion_date' => 'scheduledDeletionDate',
        'highlighted_date' => 'highlightedDate',
        'organization' => 'organization',
        'parent_score' => 'parentScore',
        'instruments' => 'instruments',
        'instruments_names' => 'instrumentsNames',
        'samples' => 'samples',
        'google_drive_file_id' => 'googleDriveFileId',
        'likes' => 'likes',
        'comments' => 'comments',
        'views' => 'views',
        'plays' => 'plays',
        'collections' => 'collections',
        'me' => 'me'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'sharing_key' => 'setSharingKey',
        'title' => 'setTitle',
        'privacy' => 'setPrivacy',
        'user' => 'setUser',
        'html_url' => 'setHtmlUrl',
        'edit_html_url' => 'setEditHtmlUrl',
        'subtitle' => 'setSubtitle',
        'lyricist' => 'setLyricist',
        'arranger' => 'setArranger',
        'composer' => 'setComposer',
        'description' => 'setDescription',
        'tags' => 'setTags',
        'creation_type' => 'setCreationType',
        'license' => 'setLicense',
        'license_text' => 'setLicenseText',
        'duration_time' => 'setDurationTime',
        'number_measures' => 'setNumberMeasures',
        'main_tempo_qpm' => 'setMainTempoQpm',
        'main_key_signature' => 'setMainKeySignature',
        'rights' => 'setRights',
        'collaborators' => 'setCollaborators',
        'creation_date' => 'setCreationDate',
        'modification_date' => 'setModificationDate',
        'publication_date' => 'setPublicationDate',
        'scheduled_deletion_date' => 'setScheduledDeletionDate',
        'highlighted_date' => 'setHighlightedDate',
        'organization' => 'setOrganization',
        'parent_score' => 'setParentScore',
        'instruments' => 'setInstruments',
        'instruments_names' => 'setInstrumentsNames',
        'samples' => 'setSamples',
        'google_drive_file_id' => 'setGoogleDriveFileId',
        'likes' => 'setLikes',
        'comments' => 'setComments',
        'views' => 'setViews',
        'plays' => 'setPlays',
        'collections' => 'setCollections',
        'me' => 'setMe'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'sharing_key' => 'getSharingKey',
        'title' => 'getTitle',
        'privacy' => 'getPrivacy',
        'user' => 'getUser',
        'html_url' => 'getHtmlUrl',
        'edit_html_url' => 'getEditHtmlUrl',
        'subtitle' => 'getSubtitle',
        'lyricist' => 'getLyricist',
        'arranger' => 'getArranger',
        'composer' => 'getComposer',
        'description' => 'getDescription',
        'tags' => 'getTags',
        'creation_type' => 'getCreationType',
        'license' => 'getLicense',
        'license_text' => 'getLicenseText',
        'duration_time' => 'getDurationTime',
        'number_measures' => 'getNumberMeasures',
        'main_tempo_qpm' => 'getMainTempoQpm',
        'main_key_signature' => 'getMainKeySignature',
        'rights' => 'getRights',
        'collaborators' => 'getCollaborators',
        'creation_date' => 'getCreationDate',
        'modification_date' => 'getModificationDate',
        'publication_date' => 'getPublicationDate',
        'scheduled_deletion_date' => 'getScheduledDeletionDate',
        'highlighted_date' => 'getHighlightedDate',
        'organization' => 'getOrganization',
        'parent_score' => 'getParentScore',
        'instruments' => 'getInstruments',
        'instruments_names' => 'getInstrumentsNames',
        'samples' => 'getSamples',
        'google_drive_file_id' => 'getGoogleDriveFileId',
        'likes' => 'getLikes',
        'comments' => 'getComments',
        'views' => 'getViews',
        'plays' => 'getPlays',
        'collections' => 'getCollections',
        'me' => 'getMe'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('sharing_key', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('privacy', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('html_url', $data ?? [], null);
        $this->setIfExists('edit_html_url', $data ?? [], null);
        $this->setIfExists('subtitle', $data ?? [], null);
        $this->setIfExists('lyricist', $data ?? [], null);
        $this->setIfExists('arranger', $data ?? [], null);
        $this->setIfExists('composer', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('creation_type', $data ?? [], null);
        $this->setIfExists('license', $data ?? [], null);
        $this->setIfExists('license_text', $data ?? [], null);
        $this->setIfExists('duration_time', $data ?? [], null);
        $this->setIfExists('number_measures', $data ?? [], null);
        $this->setIfExists('main_tempo_qpm', $data ?? [], null);
        $this->setIfExists('main_key_signature', $data ?? [], null);
        $this->setIfExists('rights', $data ?? [], null);
        $this->setIfExists('collaborators', $data ?? [], null);
        $this->setIfExists('creation_date', $data ?? [], null);
        $this->setIfExists('modification_date', $data ?? [], null);
        $this->setIfExists('publication_date', $data ?? [], null);
        $this->setIfExists('scheduled_deletion_date', $data ?? [], null);
        $this->setIfExists('highlighted_date', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('parent_score', $data ?? [], null);
        $this->setIfExists('instruments', $data ?? [], null);
        $this->setIfExists('instruments_names', $data ?? [], null);
        $this->setIfExists('samples', $data ?? [], null);
        $this->setIfExists('google_drive_file_id', $data ?? [], null);
        $this->setIfExists('likes', $data ?? [], null);
        $this->setIfExists('comments', $data ?? [], null);
        $this->setIfExists('views', $data ?? [], null);
        $this->setIfExists('plays', $data ?? [], null);
        $this->setIfExists('collections', $data ?? [], null);
        $this->setIfExists('me', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['privacy'] === null) {
            $invalidProperties[] = "'privacy' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        if ($this->container['html_url'] === null) {
            $invalidProperties[] = "'html_url' can't be null";
        }
        if ($this->container['edit_html_url'] === null) {
            $invalidProperties[] = "'edit_html_url' can't be null";
        }
        if ($this->container['collaborators'] === null) {
            $invalidProperties[] = "'collaborators' can't be null";
        }
        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        if ($this->container['instruments'] === null) {
            $invalidProperties[] = "'instruments' can't be null";
        }
        if ($this->container['instruments_names'] === null) {
            $invalidProperties[] = "'instruments_names' can't be null";
        }
        if ($this->container['samples'] === null) {
            $invalidProperties[] = "'samples' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The unique identifier of the score
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets sharing_key
     *
     * @return string|null
     */
    public function getSharingKey(): ?string
    {
        return $this->container['sharing_key'];
    }

    /**
     * Sets sharing_key
     *
     * @param string|null $sharing_key The private sharing key of the score (available when the `privacy` mode is set to `privateLink`)
     *
     * @return $this
     */
    public function setSharingKey(?string $sharing_key): static
    {
        if (is_null($sharing_key)) {
            throw new InvalidArgumentException('non-nullable sharing_key cannot be null');
        }
        $this->container['sharing_key'] = $sharing_key;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle(): string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of the score
     *
     * @return $this
     */
    public function setTitle(string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets privacy
     *
     * @return \Flat\APIClient\Model\ScorePrivacy
     */
    public function getPrivacy(): \Flat\APIClient\Model\ScorePrivacy
    {
        return $this->container['privacy'];
    }

    /**
     * Sets privacy
     *
     * @param \Flat\APIClient\Model\ScorePrivacy $privacy privacy
     *
     * @return $this
     */
    public function setPrivacy(\Flat\APIClient\Model\ScorePrivacy $privacy): static
    {
        if (is_null($privacy)) {
            throw new InvalidArgumentException('non-nullable privacy cannot be null');
        }
        $this->container['privacy'] = $privacy;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \Flat\APIClient\Model\UserPublic
     */
    public function getUser(): \Flat\APIClient\Model\UserPublic
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \Flat\APIClient\Model\UserPublic $user user
     *
     * @return $this
     */
    public function setUser(\Flat\APIClient\Model\UserPublic $user): static
    {
        if (is_null($user)) {
            throw new InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets html_url
     *
     * @return string
     */
    public function getHtmlUrl(): string
    {
        return $this->container['html_url'];
    }

    /**
     * Sets html_url
     *
     * @param string $html_url The url where the score can be viewed in a web browser
     *
     * @return $this
     */
    public function setHtmlUrl(string $html_url): static
    {
        if (is_null($html_url)) {
            throw new InvalidArgumentException('non-nullable html_url cannot be null');
        }
        $this->container['html_url'] = $html_url;

        return $this;
    }

    /**
     * Gets edit_html_url
     *
     * @return string
     */
    public function getEditHtmlUrl(): string
    {
        return $this->container['edit_html_url'];
    }

    /**
     * Sets edit_html_url
     *
     * @param string $edit_html_url The url where the score can be edited in a web browser
     *
     * @return $this
     */
    public function setEditHtmlUrl(string $edit_html_url): static
    {
        if (is_null($edit_html_url)) {
            throw new InvalidArgumentException('non-nullable edit_html_url cannot be null');
        }
        $this->container['edit_html_url'] = $edit_html_url;

        return $this;
    }

    /**
     * Gets subtitle
     *
     * @return string|null
     */
    public function getSubtitle(): ?string
    {
        return $this->container['subtitle'];
    }

    /**
     * Sets subtitle
     *
     * @param string|null $subtitle Subtitle of the score
     *
     * @return $this
     */
    public function setSubtitle(?string $subtitle): static
    {
        if (is_null($subtitle)) {
            throw new InvalidArgumentException('non-nullable subtitle cannot be null');
        }
        $this->container['subtitle'] = $subtitle;

        return $this;
    }

    /**
     * Gets lyricist
     *
     * @return string|null
     */
    public function getLyricist(): ?string
    {
        return $this->container['lyricist'];
    }

    /**
     * Sets lyricist
     *
     * @param string|null $lyricist Lyricist of the score
     *
     * @return $this
     */
    public function setLyricist(?string $lyricist): static
    {
        if (is_null($lyricist)) {
            throw new InvalidArgumentException('non-nullable lyricist cannot be null');
        }
        $this->container['lyricist'] = $lyricist;

        return $this;
    }

    /**
     * Gets arranger
     *
     * @return string|null
     */
    public function getArranger(): ?string
    {
        return $this->container['arranger'];
    }

    /**
     * Sets arranger
     *
     * @param string|null $arranger Arranger of the score
     *
     * @return $this
     */
    public function setArranger(?string $arranger): static
    {
        if (is_null($arranger)) {
            throw new InvalidArgumentException('non-nullable arranger cannot be null');
        }
        $this->container['arranger'] = $arranger;

        return $this;
    }

    /**
     * Gets composer
     *
     * @return string|null
     */
    public function getComposer(): ?string
    {
        return $this->container['composer'];
    }

    /**
     * Sets composer
     *
     * @param string|null $composer Composer of the score
     *
     * @return $this
     */
    public function setComposer(?string $composer): static
    {
        if (is_null($composer)) {
            throw new InvalidArgumentException('non-nullable composer cannot be null');
        }
        $this->container['composer'] = $composer;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description of the creation
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags Tags describing the score
     *
     * @return $this
     */
    public function setTags(?array $tags): static
    {
        if (is_null($tags)) {
            throw new InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets creation_type
     *
     * @return \Flat\APIClient\Model\ScoreCreationType|null
     */
    public function getCreationType(): ?\Flat\APIClient\Model\ScoreCreationType
    {
        return $this->container['creation_type'];
    }

    /**
     * Sets creation_type
     *
     * @param \Flat\APIClient\Model\ScoreCreationType|null $creation_type creation_type
     *
     * @return $this
     */
    public function setCreationType(?\Flat\APIClient\Model\ScoreCreationType $creation_type): static
    {
        if (is_null($creation_type)) {
            array_push($this->openAPINullablesSetToNull, 'creation_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('creation_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['creation_type'] = $creation_type;

        return $this;
    }

    /**
     * Gets license
     *
     * @return \Flat\APIClient\Model\ScoreLicense|null
     */
    public function getLicense(): ?\Flat\APIClient\Model\ScoreLicense
    {
        return $this->container['license'];
    }

    /**
     * Sets license
     *
     * @param \Flat\APIClient\Model\ScoreLicense|null $license license
     *
     * @return $this
     */
    public function setLicense(?\Flat\APIClient\Model\ScoreLicense $license): static
    {
        if (is_null($license)) {
            array_push($this->openAPINullablesSetToNull, 'license');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('license', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['license'] = $license;

        return $this;
    }

    /**
     * Gets license_text
     *
     * @return string|null
     */
    public function getLicenseText(): ?string
    {
        return $this->container['license_text'];
    }

    /**
     * Sets license_text
     *
     * @param string|null $license_text Additional license text written on the exported/printed score
     *
     * @return $this
     */
    public function setLicenseText(?string $license_text): static
    {
        if (is_null($license_text)) {
            throw new InvalidArgumentException('non-nullable license_text cannot be null');
        }
        $this->container['license_text'] = $license_text;

        return $this;
    }

    /**
     * Gets duration_time
     *
     * @return float|null
     */
    public function getDurationTime(): ?float
    {
        return $this->container['duration_time'];
    }

    /**
     * Sets duration_time
     *
     * @param float|null $duration_time In seconds, an approximative duration of the score
     *
     * @return $this
     */
    public function setDurationTime(?float $duration_time): static
    {
        if (is_null($duration_time)) {
            throw new InvalidArgumentException('non-nullable duration_time cannot be null');
        }
        $this->container['duration_time'] = $duration_time;

        return $this;
    }

    /**
     * Gets number_measures
     *
     * @return int|null
     */
    public function getNumberMeasures(): ?int
    {
        return $this->container['number_measures'];
    }

    /**
     * Sets number_measures
     *
     * @param int|null $number_measures The number of measures in the score
     *
     * @return $this
     */
    public function setNumberMeasures(?int $number_measures): static
    {
        if (is_null($number_measures)) {
            throw new InvalidArgumentException('non-nullable number_measures cannot be null');
        }
        $this->container['number_measures'] = $number_measures;

        return $this;
    }

    /**
     * Gets main_tempo_qpm
     *
     * @return float|null
     */
    public function getMainTempoQpm(): ?float
    {
        return $this->container['main_tempo_qpm'];
    }

    /**
     * Sets main_tempo_qpm
     *
     * @param float|null $main_tempo_qpm The main tempo of the score (in QPM)
     *
     * @return $this
     */
    public function setMainTempoQpm(?float $main_tempo_qpm): static
    {
        if (is_null($main_tempo_qpm)) {
            throw new InvalidArgumentException('non-nullable main_tempo_qpm cannot be null');
        }
        $this->container['main_tempo_qpm'] = $main_tempo_qpm;

        return $this;
    }

    /**
     * Gets main_key_signature
     *
     * @return float|null
     */
    public function getMainKeySignature(): ?float
    {
        return $this->container['main_key_signature'];
    }

    /**
     * Sets main_key_signature
     *
     * @param float|null $main_key_signature The main key signature of the score (expressed between -7 and 7).
     *
     * @return $this
     */
    public function setMainKeySignature(?float $main_key_signature): static
    {
        if (is_null($main_key_signature)) {
            throw new InvalidArgumentException('non-nullable main_key_signature cannot be null');
        }
        $this->container['main_key_signature'] = $main_key_signature;

        return $this;
    }

    /**
     * Gets rights
     *
     * @return \Flat\APIClient\Model\ResourceRights|null
     */
    public function getRights(): ?\Flat\APIClient\Model\ResourceRights
    {
        return $this->container['rights'];
    }

    /**
     * Sets rights
     *
     * @param \Flat\APIClient\Model\ResourceRights|null $rights rights
     *
     * @return $this
     */
    public function setRights(?\Flat\APIClient\Model\ResourceRights $rights): static
    {
        if (is_null($rights)) {
            throw new InvalidArgumentException('non-nullable rights cannot be null');
        }
        $this->container['rights'] = $rights;

        return $this;
    }

    /**
     * Gets collaborators
     *
     * @return \Flat\APIClient\Model\ResourceCollaborator[]
     */
    public function getCollaborators(): array
    {
        return $this->container['collaborators'];
    }

    /**
     * Sets collaborators
     *
     * @param \Flat\APIClient\Model\ResourceCollaborator[] $collaborators The list of the collaborators of the score
     *
     * @return $this
     */
    public function setCollaborators(array $collaborators): static
    {
        if (is_null($collaborators)) {
            throw new InvalidArgumentException('non-nullable collaborators cannot be null');
        }
        $this->container['collaborators'] = $collaborators;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime
     */
    public function getCreationDate(): \DateTime
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime $creation_date The date when the score was created
     *
     * @return $this
     */
    public function setCreationDate(\DateTime $creation_date): static
    {
        if (is_null($creation_date)) {
            throw new InvalidArgumentException('non-nullable creation_date cannot be null');
        }
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets modification_date
     *
     * @return \DateTime|null
     */
    public function getModificationDate(): ?\DateTime
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     *
     * @param \DateTime|null $modification_date The date of the last revision of the score
     *
     * @return $this
     */
    public function setModificationDate(?\DateTime $modification_date): static
    {
        if (is_null($modification_date)) {
            throw new InvalidArgumentException('non-nullable modification_date cannot be null');
        }
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets publication_date
     *
     * @return \DateTime|null
     */
    public function getPublicationDate(): ?\DateTime
    {
        return $this->container['publication_date'];
    }

    /**
     * Sets publication_date
     *
     * @param \DateTime|null $publication_date The date when the score was published on Flat
     *
     * @return $this
     */
    public function setPublicationDate(?\DateTime $publication_date): static
    {
        if (is_null($publication_date)) {
            throw new InvalidArgumentException('non-nullable publication_date cannot be null');
        }
        $this->container['publication_date'] = $publication_date;

        return $this;
    }

    /**
     * Gets scheduled_deletion_date
     *
     * @return \DateTime|null
     */
    public function getScheduledDeletionDate(): ?\DateTime
    {
        return $this->container['scheduled_deletion_date'];
    }

    /**
     * Sets scheduled_deletion_date
     *
     * @param \DateTime|null $scheduled_deletion_date The date when the score will be definitively deleted. This date can be in the past if the score will be deleted at the next deletion batch, in this case you can display something like \"Deleted shortly\".  Schedule:  * For all paying users, the scores will be definitively deleted after 90 days. * For free users, the scores are no longer available after 24 hours, an can be restored with a paying account up to 90 days.
     *
     * @return $this
     */
    public function setScheduledDeletionDate(?\DateTime $scheduled_deletion_date): static
    {
        if (is_null($scheduled_deletion_date)) {
            throw new InvalidArgumentException('non-nullable scheduled_deletion_date cannot be null');
        }
        $this->container['scheduled_deletion_date'] = $scheduled_deletion_date;

        return $this;
    }

    /**
     * Gets highlighted_date
     *
     * @return \DateTime|null
     */
    public function getHighlightedDate(): ?\DateTime
    {
        return $this->container['highlighted_date'];
    }

    /**
     * Sets highlighted_date
     *
     * @param \DateTime|null $highlighted_date The date when the score was highlighted (featured) on our community
     *
     * @return $this
     */
    public function setHighlightedDate(?\DateTime $highlighted_date): static
    {
        if (is_null($highlighted_date)) {
            throw new InvalidArgumentException('non-nullable highlighted_date cannot be null');
        }
        $this->container['highlighted_date'] = $highlighted_date;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization(): ?string
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization If the score has been created in an organization, the identifier of this organization. This property is especially used with the score privacy `organizationPublic`.
     *
     * @return $this
     */
    public function setOrganization(?string $organization): static
    {
        if (is_null($organization)) {
            throw new InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets parent_score
     *
     * @return string|null
     */
    public function getParentScore(): ?string
    {
        return $this->container['parent_score'];
    }

    /**
     * Sets parent_score
     *
     * @param string|null $parent_score If the score has been forked, the unique identifier of the parent score.
     *
     * @return $this
     */
    public function setParentScore(?string $parent_score): static
    {
        if (is_null($parent_score)) {
            throw new InvalidArgumentException('non-nullable parent_score cannot be null');
        }
        $this->container['parent_score'] = $parent_score;

        return $this;
    }

    /**
     * Gets instruments
     *
     * @return string[]
     */
    public function getInstruments(): array
    {
        return $this->container['instruments'];
    }

    /**
     * Sets instruments
     *
     * @param string[] $instruments An array of the instrument identifiers used in the last version of the score. This is mainly used to display a list of the instruments in the Flat's UI or instruments icons. The format of the strings is `{instrument-group}.{instrument-id}`.
     *
     * @return $this
     */
    public function setInstruments(array $instruments): static
    {
        if (is_null($instruments)) {
            throw new InvalidArgumentException('non-nullable instruments cannot be null');
        }
        $this->container['instruments'] = $instruments;

        return $this;
    }

    /**
     * Gets instruments_names
     *
     * @return string[]
     */
    public function getInstrumentsNames(): array
    {
        return $this->container['instruments_names'];
    }

    /**
     * Sets instruments_names
     *
     * @param string[] $instruments_names An array of the instrument names used in the last version of the score. This list is localized and ready-to-display and will match the indexes from the `instruments` list.
     *
     * @return $this
     */
    public function setInstrumentsNames(array $instruments_names): static
    {
        if (is_null($instruments_names)) {
            throw new InvalidArgumentException('non-nullable instruments_names cannot be null');
        }
        $this->container['instruments_names'] = $instruments_names;

        return $this;
    }

    /**
     * Gets samples
     *
     * @return string[]
     */
    public function getSamples(): array
    {
        return $this->container['samples'];
    }

    /**
     * Sets samples
     *
     * @param string[] $samples An array of the audio samples identifiers used the different score parts. The format of the strings is `{instrument-group}.{sample-id}`.
     *
     * @return $this
     */
    public function setSamples(array $samples): static
    {
        if (is_null($samples)) {
            throw new InvalidArgumentException('non-nullable samples cannot be null');
        }
        $this->container['samples'] = $samples;

        return $this;
    }

    /**
     * Gets google_drive_file_id
     *
     * @return string|null
     */
    public function getGoogleDriveFileId(): ?string
    {
        return $this->container['google_drive_file_id'];
    }

    /**
     * Sets google_drive_file_id
     *
     * @param string|null $google_drive_file_id If the user uses Google Drive and the score exists on Google Drive, this field will contain the unique identifier of the Flat score on Google Drive. You can access the document using the url: `https://drive.google.com/open?id={googleDriveFileId}`
     *
     * @return $this
     */
    public function setGoogleDriveFileId(?string $google_drive_file_id): static
    {
        if (is_null($google_drive_file_id)) {
            throw new InvalidArgumentException('non-nullable google_drive_file_id cannot be null');
        }
        $this->container['google_drive_file_id'] = $google_drive_file_id;

        return $this;
    }

    /**
     * Gets likes
     *
     * @return \Flat\APIClient\Model\ScoreLikesCounts|null
     */
    public function getLikes(): ?\Flat\APIClient\Model\ScoreLikesCounts
    {
        return $this->container['likes'];
    }

    /**
     * Sets likes
     *
     * @param \Flat\APIClient\Model\ScoreLikesCounts|null $likes likes
     *
     * @return $this
     */
    public function setLikes(?\Flat\APIClient\Model\ScoreLikesCounts $likes): static
    {
        if (is_null($likes)) {
            throw new InvalidArgumentException('non-nullable likes cannot be null');
        }
        $this->container['likes'] = $likes;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return \Flat\APIClient\Model\ScoreCommentsCounts|null
     */
    public function getComments(): ?\Flat\APIClient\Model\ScoreCommentsCounts
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param \Flat\APIClient\Model\ScoreCommentsCounts|null $comments comments
     *
     * @return $this
     */
    public function setComments(?\Flat\APIClient\Model\ScoreCommentsCounts $comments): static
    {
        if (is_null($comments)) {
            throw new InvalidArgumentException('non-nullable comments cannot be null');
        }
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets views
     *
     * @return \Flat\APIClient\Model\ScoreViewsCounts|null
     */
    public function getViews(): ?\Flat\APIClient\Model\ScoreViewsCounts
    {
        return $this->container['views'];
    }

    /**
     * Sets views
     *
     * @param \Flat\APIClient\Model\ScoreViewsCounts|null $views views
     *
     * @return $this
     */
    public function setViews(?\Flat\APIClient\Model\ScoreViewsCounts $views): static
    {
        if (is_null($views)) {
            throw new InvalidArgumentException('non-nullable views cannot be null');
        }
        $this->container['views'] = $views;

        return $this;
    }

    /**
     * Gets plays
     *
     * @return \Flat\APIClient\Model\ScorePlaysCounts|null
     */
    public function getPlays(): ?\Flat\APIClient\Model\ScorePlaysCounts
    {
        return $this->container['plays'];
    }

    /**
     * Sets plays
     *
     * @param \Flat\APIClient\Model\ScorePlaysCounts|null $plays plays
     *
     * @return $this
     */
    public function setPlays(?\Flat\APIClient\Model\ScorePlaysCounts $plays): static
    {
        if (is_null($plays)) {
            throw new InvalidArgumentException('non-nullable plays cannot be null');
        }
        $this->container['plays'] = $plays;

        return $this;
    }

    /**
     * Gets collections
     *
     * @return string[]|null
     */
    public function getCollections(): ?array
    {
        return $this->container['collections'];
    }

    /**
     * Sets collections
     *
     * @param string[]|null $collections The List of parent collections, which includes all the collections this score is included. Please note that you might not have access to all of them.
     *
     * @return $this
     */
    public function setCollections(?array $collections): static
    {
        if (is_null($collections)) {
            throw new InvalidArgumentException('non-nullable collections cannot be null');
        }
        $this->container['collections'] = $collections;

        return $this;
    }

    /**
     * Gets me
     *
     * @return \Flat\APIClient\Model\ScoreDetailsAllOfMe|null
     */
    public function getMe(): ?\Flat\APIClient\Model\ScoreDetailsAllOfMe
    {
        return $this->container['me'];
    }

    /**
     * Sets me
     *
     * @param \Flat\APIClient\Model\ScoreDetailsAllOfMe|null $me me
     *
     * @return $this
     */
    public function setMe(?\Flat\APIClient\Model\ScoreDetailsAllOfMe $me): static
    {
        if (is_null($me)) {
            throw new InvalidArgumentException('non-nullable me cannot be null');
        }
        $this->container['me'] = $me;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


